import esbuild from 'esbuild';
import process from 'node:process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: obsidian-publishing-manager
*/`;

const production = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: { js: banner },
  bundle: true,
  entryPoints: ['src/main.ts'],
  external: [
    'obsidian',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr'
  ],
  format: 'cjs',
  logLevel: 'info',
  minify: production,
  outfile: 'main.js',
  platform: 'browser',
  sourcemap: production ? false : 'inline',
  target: 'es2021',
  treeShaking: true
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
