/**
 * Pure EXP-001–EXP-008 export contracts and serializers. Export planning remains data-only: this
 * module knows nothing about Obsidian, vault files, repositories, or binary content. The caller
 * supplies a fixed generation time so the exact preview bytes are also the exact applied bytes.
 */

export const PUBLISHING_EXPORT_SCHEMA_VERSION = 1;
export const PUBLISHING_EXPORT_GENERATOR_VERSION = '0.1.0';

export const PUBLISHING_CSV_DATASETS = [
  'tasks',
  'isbns',
  'prices',
  'platforms',
  'editions',
  'canonical-sales-lines',
  'attributed-sales-aggregates'
] as const;

export type PublishingCsvDataset = (typeof PUBLISHING_CSV_DATASETS)[number];
export type PublishingExportFormat = 'csv' | 'ics' | 'json' | 'markdown';

export interface ExportMetadata {
  readonly generatorVersion: string;
  readonly schemaVersion: number;
  readonly generatedAt: string;
  readonly scope: { readonly type: 'book'; readonly id: string; readonly label: string };
  readonly warnings: readonly string[];
}

export interface PortableExportRecord {
  readonly id: string;
  readonly type: string;
  readonly schemaVersion: number;
  readonly fields: Readonly<Record<string, unknown>>;
}

export interface ReadinessExportResult {
  readonly code: string;
  readonly version: number;
  readonly state: string;
  readonly severity: string;
  readonly evidence: string;
  readonly remedy?: string;
}

export interface DossierExportInput {
  readonly metadata: ExportMetadata;
  readonly book: PortableExportRecord;
  readonly records: readonly PortableExportRecord[];
  readonly readiness: {
    readonly state: string;
    readonly score: number | null;
    readonly confidence: number | null;
    readonly rulePackCode: string;
    readonly rulePackVersion: number;
    readonly results: readonly ReadinessExportResult[];
  };
}

export interface CsvExportInput {
  readonly metadata: ExportMetadata;
  readonly dataset: PublishingCsvDataset;
  readonly columns: readonly string[];
  readonly rows: readonly Readonly<Record<string, unknown>>[];
}

export interface JsonExportInput {
  readonly metadata: ExportMetadata;
  readonly records: readonly PortableExportRecord[];
}

export interface CalendarExportEvent {
  readonly id: string;
  readonly date: string;
  readonly title: string;
  readonly kind: string;
  readonly recordId: string;
}

/** Human-readable dossier with explicit evidence and no hidden binary or note-body payload. */
export function serializeMarkdownDossier(input: DossierExportInput): string {
  const lines = [
    '---',
    `generator: publishing-manager/${input.metadata.generatorVersion}`,
    `export-schema: ${input.metadata.schemaVersion}`,
    `generated-at: ${input.metadata.generatedAt}`,
    `scope-type: ${input.metadata.scope.type}`,
    `scope-id: ${yamlText(input.metadata.scope.id)}`,
    '---',
    '',
    `# Publishing dossier — ${input.metadata.scope.label}`,
    '',
    '> Local snapshot generated by Publishing Manager. Canonical vault notes remain authoritative.',
    '',
    '## Export evidence',
    '',
    `- Generator: Publishing Manager ${input.metadata.generatorVersion}`,
    `- Export schema: ${input.metadata.schemaVersion}`,
    `- Generated: ${input.metadata.generatedAt}`,
    `- Scope: book ${input.metadata.scope.id}`,
    `- Warnings: ${input.metadata.warnings.length}`,
    '',
    '## Book',
    '',
    markdownFields(input.book.fields),
    '',
    '## Readiness',
    '',
    `- State: ${input.readiness.state}`,
    `- Score: ${input.readiness.score === null ? '—' : `${input.readiness.score}%`}`,
    `- Confidence: ${input.readiness.confidence === null ? '—' : `${input.readiness.confidence}%`}`,
    `- Rule pack: ${input.readiness.rulePackCode} v${input.readiness.rulePackVersion}`,
    ''
  ];
  if (input.readiness.results.length === 0) lines.push('_No readiness results._', '');
  for (const result of input.readiness.results) {
    lines.push(
      `### ${result.code} v${result.version} — ${result.state}`,
      '',
      `- Severity: ${result.severity}`,
      `- Evidence: ${result.evidence}`,
      ...(result.remedy === undefined ? [] : [`- Remedy: ${result.remedy}`]),
      ''
    );
  }
  lines.push('## Project inventory', '');
  const counts = new Map<string, number>();
  for (const record of input.records) counts.set(record.type, (counts.get(record.type) ?? 0) + 1);
  if (counts.size === 0) lines.push('_No related records._', '');
  else
    for (const [type, count] of [...counts].sort(([a], [b]) => a.localeCompare(b)))
      lines.push(`- ${type}: ${count}`);
  lines.push('', '## Warnings', '');
  if (input.metadata.warnings.length === 0) lines.push('- None.');
  else for (const warning of input.metadata.warnings) lines.push(`- ${escapeMarkdown(warning)}`);
  return `${lines.join('\n').trimEnd()}\n`;
}

/** RFC 4180-compatible rows with export evidence repeated even when consumers split the file. */
export function serializeCsvTable(input: CsvExportInput): string {
  const evidenceColumns = [
    'generator-version',
    'export-schema-version',
    'generated-at',
    'scope-type',
    'scope-id',
    'warnings'
  ];
  const columns = [...evidenceColumns, ...input.columns];
  const evidence = {
    'generator-version': input.metadata.generatorVersion,
    'export-schema-version': input.metadata.schemaVersion,
    'generated-at': input.metadata.generatedAt,
    'scope-type': input.metadata.scope.type,
    'scope-id': input.metadata.scope.id,
    warnings: input.metadata.warnings.join(' | ')
  };
  const rows = input.rows.length === 0 ? [{}] : input.rows;
  return `${[
    columns.map(csvCell).join(','),
    ...rows.map((row) =>
      columns.map((column) => csvCell({ ...evidence, ...row }[column])).join(',')
    )
  ].join('\r\n')}\r\n`;
}

/** Versioned project graph with recursively sorted keys, stable IDs, and explicit relationships. */
export function serializeJsonProject(input: JsonExportInput): string {
  return `${stableStringify({
    format: 'publishing-manager-project-export',
    schemaVersion: input.metadata.schemaVersion,
    generatorVersion: input.metadata.generatorVersion,
    generatedAt: input.metadata.generatedAt,
    scope: input.metadata.scope,
    warnings: input.metadata.warnings,
    records: [...input.records].sort((a, b) =>
      `${a.type}:${a.id}`.localeCompare(`${b.type}:${b.id}`)
    )
  })}\n`;
}

/** Local all-day ICS snapshot carrying the same generator, schema, scope, and warning evidence. */
export function serializePublishingIcs(
  metadata: ExportMetadata,
  events: readonly CalendarExportEvent[]
): string {
  const timestamp = metadata.generatedAt
    .replace(/\.\d{3}Z$/u, 'Z')
    .replaceAll('-', '')
    .replaceAll(':', '');
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:-//Publishing Manager ${metadata.generatorVersion}//Local Export//EN`,
    'CALSCALE:GREGORIAN',
    `X-PM-EXPORT-SCHEMA:${metadata.schemaVersion}`,
    `X-PM-GENERATED-AT:${escapeIcs(metadata.generatedAt)}`,
    `X-PM-SCOPE:${escapeIcs(`${metadata.scope.type}:${metadata.scope.id}`)}`
  ];
  for (const warning of metadata.warnings) lines.push(`X-PM-WARNING:${escapeIcs(warning)}`);
  for (const event of [...events].sort(
    (a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id)
  )) {
    lines.push(
      'BEGIN:VEVENT',
      `UID:${escapeIcs(event.id)}@publishing-manager.local`,
      `DTSTAMP:${timestamp}`,
      `DTSTART;VALUE=DATE:${event.date.replaceAll('-', '')}`,
      `DTEND;VALUE=DATE:${nextDate(event.date).replaceAll('-', '')}`,
      `SUMMARY:${escapeIcs(event.title)}`,
      `DESCRIPTION:${escapeIcs(`${event.kind} · ${event.recordId}`)}`,
      'END:VEVENT'
    );
  }
  lines.push('END:VCALENDAR', '');
  return lines.join('\r\n');
}

/** Stable pretty JSON is shared by previews and file writes so serialization cannot drift. */
export function stableStringify(value: unknown): string {
  return JSON.stringify(sortRecursively(value), undefined, 2);
}

function sortRecursively(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortRecursively);
  if (typeof value !== 'object' || value === null) return value;
  return Object.fromEntries(
    Object.entries(value as Readonly<Record<string, unknown>>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => [key, sortRecursively(item)])
  );
}

function markdownFields(fields: Readonly<Record<string, unknown>>): string {
  const entries = Object.entries(fields).sort(([a], [b]) => a.localeCompare(b));
  return entries.length === 0
    ? '_No exported fields._'
    : entries.map(([key, value]) => `- ${key}: ${escapeMarkdown(displayValue(value))}`).join('\n');
}

function displayValue(value: unknown): string {
  if (value === undefined || value === null) return '—';
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    return String(value);
  return stableStringify(value).replaceAll('\n', ' ');
}

function csvCell(value: unknown): string {
  const text = displayValue(value);
  return /[",\r\n]/u.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

function yamlText(value: string): string {
  return JSON.stringify(value);
}

function escapeMarkdown(value: string): string {
  return value.replaceAll('\n', ' ').replace(/([\\`*_{}[\]()#+.!|>-])/gu, '\\$1');
}

function escapeIcs(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll(';', '\\;')
    .replaceAll(',', '\\,')
    .replaceAll('\r\n', '\\n')
    .replaceAll('\n', '\\n');
}

function nextDate(value: string): string {
  if (!/^\d{4}-\d{2}-\d{2}$/u.test(value)) throw new Error(`Invalid calendar date ${value}.`);
  const year = Number(value.slice(0, 4));
  const month = Number(value.slice(5, 7));
  const day = Number(value.slice(8, 10));
  const source = new Date(Date.UTC(year, month - 1, day));
  if (
    source.getUTCFullYear() !== year ||
    source.getUTCMonth() !== month - 1 ||
    source.getUTCDate() !== day
  )
    throw new Error(`Invalid calendar date ${value}.`);
  const date = new Date(Date.UTC(year, month - 1, day + 1));
  return date.toISOString().slice(0, 10);
}
